In [1]:
#第一题
#输入示例7
import math
a=int(input())
if a==1:
    print("不是质数")
else:
    flag=1
    for i in range(2,int(math.sqrt(a))+1):
        if a%i==0:
            flag=0
            break
    if flag==1:
        print("是质数")
    else:
        print("不是质数")

是质数


In [2]:
#第二题
#插入排序
#输入示例30个介于0到10000的int
import numpy as np
N=30
a=np.random.randint(0,10000,N)
#print(a)
for i in range(1,N):
    t=a[i]
    j=i-1
    while t<a[j] and j>=0:#python的for不会结束时增加1
        a[j+1]=a[j]
        j=j-1
    a[j+1]=t
print(a)

[ 103  741 1187 1287 1427 1565 1669 1753 2127 2756 2824 2978 3411 3508
 3751 4166 4547 5104 5370 5553 5996 6487 6676 6927 7690 7928 8844 8979
 9231 9713]


In [3]:
#第三题
#选择排序
#输入示例30个介于0到10000的int
import numpy as np
N=30
a=np.random.randint(0,10000,N)
for i in range(0,N):
    t=i
    for j in range(i,N):
        if a[j]<a[t]:
            t=j
    a[i],a[t]=a[t],a[i]
print(a)

[  36 1125 1271 2227 2647 3026 3619 3653 4388 4453 4583 5272 5615 5645
 5655 5733 6817 6942 7566 7566 7773 7901 8029 8154 8445 8839 8978 9131
 9503 9998]


In [4]:
#第四题
#快速排序
#输入示例30个介于0到10000的int
import sys
sys.setrecursionlimit(10000)
def partition(a,p,r):
    x=a[r]
    i=p-1
    for j in range(p,r):
        if a[j]<=x:
            i=i+1
            a[i],a[j]=a[j],a[i]
    a[i+1],a[r]=a[r],a[i+1]
    return i+1
def quicksort(a,p,r):
    if p<r:
        k=partition(a,p,r)
        quicksort(a,p,k-1)
        quicksort(a,k+1,r)
import numpy as np
N=30
a=np.random.randint(0,10000,N)
quicksort(a,0,N-1)
print(a)

[ 701  790  944 1405 1452 1519 1596 2092 2880 2925 2954 4109 4128 4248
 4458 4649 5267 5551 5888 6466 6692 7234 7468 7837 8387 9229 9274 9600
 9686 9888]


In [8]:
#第五题
#输入数据规模为100时
import sys
import numpy as np
import time
sys.setrecursionlimit(10000)
np.set_printoptions(threshold=2)

def selectionsort(a):
    for i in range(0,N):
        t=i
        for j in range(i,N):
            if a[j]<a[t]:
                t=j
        a[i],a[t]=a[t],a[i]

def mergesort(a,p,r):
    if p<r:
        mid=int((p+r)/2)
        mergesort(a,p,mid)
        mergesort(a,mid+1,r)
        merge(a,p,mid,r)
def merge(a,p,mid,r):
    a1=list(a[p:mid+1])
    a1.append(100000)
    a2=list(a[mid+1:r+1])
    a2.append(100000)
    i=j=k=0
    while not(i==len(a1)-1 and j==len(a2)-1):
        if a1[i]>a2[j]:
            a[p+k]=a2[j]
            j=j+1
        else:
            a[p+k]=a1[i]
            i=i+1
        k=k+1

def bubblesort(a):
    for i in range(N-2,0-1,-1):
        for j in range(0,i+1):
            if a[j]>a[j+1]:
                a[j],a[j+1]=a[j+1],a[j]        

N=100

a=np.random.randint(0,10000,N)
print("数组原先为",end='')
print(a)
start=time.perf_counter()
selectionsort(a)
end=time.perf_counter()
print("选择排序后的数列，排序开销为%.6f秒"%(end-start))
print(a)
print()

b=np.random.randint(0,10000,N)
print("数组原先为",end='')
print(b)
start=time.perf_counter()
mergesort(b,0,N-1)
end=time.perf_counter()
print("归并排序后的数列，排序开销为%.6f秒"%(end-start))
print(b)
print()

c=np.random.randint(0,10000,N)
print("数组原先为",end='')
print(c)
start=time.perf_counter()
bubblesort(c)
end=time.perf_counter()
print("冒泡排序后的数列，排序开销为%.6f秒"%(end-start))
print(c)

数组原先为[4138 8303 9664 ... 8928 3813 6501]
选择排序后的数列，排序开销为0.001254秒
[  34  129  233 ... 9807 9871 9997]

数组原先为[2602 7226 3067 ...  272 1699 2032]
归并排序后的数列，排序开销为0.000667秒
[ 170  204  272 ... 9711 9928 9940]

数组原先为[1295 9557 3375 ... 1144 3850 8622]
冒泡排序后的数列，排序开销为0.003676秒
[ 335  557  688 ... 9863 9920 9969]


In [9]:
#第五题
#输入数据规模为1000时
import sys
import numpy as np
import time
sys.setrecursionlimit(10000)
np.set_printoptions(threshold=2)

def selectionsort(a):
    for i in range(0,N):
        t=i
        for j in range(i,N):
            if a[j]<a[t]:
                t=j
        a[i],a[t]=a[t],a[i]

def mergesort(a,p,r):
    if p<r:
        mid=int((p+r)/2)
        mergesort(a,p,mid)
        mergesort(a,mid+1,r)
        merge(a,p,mid,r)
def merge(a,p,mid,r):
    a1=list(a[p:mid+1])
    a1.append(100000)
    a2=list(a[mid+1:r+1])
    a2.append(100000)
    i=j=k=0
    while not(i==len(a1)-1 and j==len(a2)-1):
        if a1[i]>a2[j]:
            a[p+k]=a2[j]
            j=j+1
        else:
            a[p+k]=a1[i]
            i=i+1
        k=k+1

def bubblesort(a):
    for i in range(N-2,0-1,-1):
        for j in range(0,i+1):
            if a[j]>a[j+1]:
                a[j],a[j+1]=a[j+1],a[j]        

N=1000

a=np.random.randint(0,10000,N)
print("数组原先为",end='')
print(a)
start=time.perf_counter()
selectionsort(a)
end=time.perf_counter()
print("选择排序后的数列，排序开销为%.6f秒"%(end-start))
print(a)
print()

b=np.random.randint(0,10000,N)
print("数组原先为",end='')
print(b)
start=time.perf_counter()
mergesort(b,0,N-1)
end=time.perf_counter()
print("归并排序后的数列，排序开销为%.6f秒"%(end-start))
print(b)
print()

c=np.random.randint(0,10000,N)
print("数组原先为",end='')
print(c)
start=time.perf_counter()
bubblesort(c)
end=time.perf_counter()
print("冒泡排序后的数列，排序开销为%.6f秒"%(end-start))
print(c)

数组原先为[3321  532 2781 ... 4473 9857 1708]
选择排序后的数列，排序开销为0.118592秒
[   0    7   22 ... 9991 9992 9992]

数组原先为[2993 6041 8263 ... 8669 6231 8318]
归并排序后的数列，排序开销为0.006003秒
[   6    7   13 ... 9961 9977 9985]

数组原先为[7735 3489  953 ...  782 9606 6651]
冒泡排序后的数列，排序开销为0.220302秒
[   1    8   21 ... 9958 9962 9988]


In [10]:
#第五题
#输入数据规模为10000时
import sys
import numpy as np
import time
sys.setrecursionlimit(10000)
np.set_printoptions(threshold=2)

def selectionsort(a):
    for i in range(0,N):
        t=i
        for j in range(i,N):
            if a[j]<a[t]:
                t=j
        a[i],a[t]=a[t],a[i]

def mergesort(a,p,r):
    if p<r:
        mid=int((p+r)/2)
        mergesort(a,p,mid)
        mergesort(a,mid+1,r)
        merge(a,p,mid,r)
def merge(a,p,mid,r):
    a1=list(a[p:mid+1])
    a1.append(100000)
    a2=list(a[mid+1:r+1])
    a2.append(100000)
    i=j=k=0
    while not(i==len(a1)-1 and j==len(a2)-1):
        if a1[i]>a2[j]:
            a[p+k]=a2[j]
            j=j+1
        else:
            a[p+k]=a1[i]
            i=i+1
        k=k+1

def bubblesort(a):
    for i in range(N-2,0-1,-1):
        for j in range(0,i+1):
            if a[j]>a[j+1]:
                a[j],a[j+1]=a[j+1],a[j]        

N=10000

a=np.random.randint(0,10000,N)
print("数组原先为",end='')
print(a)
start=time.perf_counter()
selectionsort(a)
end=time.perf_counter()
print("选择排序后的数列，排序开销为%.6f秒"%(end-start))
print(a)
print()

b=np.random.randint(0,10000,N)
print("数组原先为",end='')
print(b)
start=time.perf_counter()
mergesort(b,0,N-1)
end=time.perf_counter()
print("归并排序后的数列，排序开销为%.6f秒"%(end-start))
print(b)
print()

c=np.random.randint(0,10000,N)
print("数组原先为",end='')
print(c)
start=time.perf_counter()
bubblesort(c)
end=time.perf_counter()
print("冒泡排序后的数列，排序开销为%.6f秒"%(end-start))
print(c)

数组原先为[7994 7065 2761 ... 3447 5002 7119]
选择排序后的数列，排序开销为9.569539秒
[   0    4    5 ... 9996 9997 9998]

数组原先为[4160 9581 6982 ... 9145 5564 9472]
归并排序后的数列，排序开销为0.070698秒
[   0    1    3 ... 9996 9996 9996]

数组原先为[9151 2206 5263 ...  453 7962  363]
冒泡排序后的数列，排序开销为21.214894秒
[   0    0    0 ... 9998 9999 9999]


给定一个数据规模为n的数组，数据规模增大10倍
选择排序：原址排序，时间复杂度为Ω(n^2)，时间开销增加约100倍
归并排序：不是原址排序，时间复杂度为Ω(nlog(n))，时间开销增加约20倍
冒泡排序：原址排序，时间复杂度为Ω(n^2)，时间开销增加约100倍

In [6]:
#第六题
import datetime
print(datetime.datetime.now())

2024-10-15 23:24:48.559316


In [16]:
#第七题
import pandas as pd
import numpy as np
df=pd.read_csv('stuGrade.csv')
#print(df)
print("语文平均分 %.2f"%np.mean(df['chinese'].values))
print("数学平均分 %.2f"%np.mean(df['math'].values))
print("英语平均分 %.2f"%np.mean(df['english'].values))



#第八题
import datetime
import time
with open("my.txt",'w',encoding="utf-8") as f:
    # f.write("语文")
    f.write("10235501426,"+"娄屹宏"+"\n")

    f.write("%.2f,%.2f,%.2f\n"%(np.mean(df['chinese'].values),
                                np.mean(df['math'].values),
                                np.mean(df['english'].values)))

    f.write(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))+'\n')    
    time.sleep(2)
    f.write(str(datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")))  

语文平均分 82.60
数学平均分 81.00
英语平均分 81.80
